version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
    - echo Installing node
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'